version: '3'
networks:
 connector:
   driver: bridge

services:
  consul:
    image: gliderlabs/consul-server:latest
    container_name: consul
    hostname: consul
    ports:
      - "8500:8500"
      - "8600:53/udp"
    expose:
      - "8500"
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
      - "8400"
      - "8600"
      - "8600/upd"
    networks:
      connector:
       aliases:
        - consul
    environment:
      - SERVICE_NAME=consul
    volumes:
      - /data/consul/data:/consul/data
      - /data/consul/config:/consul/config
    command: "-advertise=${MYHOST} -server -bootstrap -client 0.0.0.0"

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    hostname: ${MYHOST}
    depends_on:
     - consul
    networks:
      connector:
       aliases:
        - registrator
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command: "-ip ${MYHOST} consul://${MYHOST}:8500"

  app:
    image: tutum/hello-world:latest
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: production
      SERVICE_80_NAME: http
      SERVICE_80_CHECK_HTTP: .
      SERVICE_80_CHECK_INTERVAL: 15s
    ports:
      - "80"

  lb:
    build: ./
    links:
     - consul
    ports:
     - "80:80"


